### ISSUE TITLE
dmc2gym has no attribute 'env_specs'

### ISSUE THREAD

**Issue by MyIDis12138** [denisyarats/dmc2gym#17]
Traceback (most recent call last):
  File "/home/yang/dmcontrol-generalization-benchmark/src/train.py", line 150, in <module>
    main(args)
  File "/home/yang/dmcontrol-generalization-benchmark/src/train.py", line 50, in main
    mode='train'
  File "/home/yang/dmcontrol-generalization-benchmark/src/env/wrappers.py", line 48, in make_env
    background_dataset_paths=paths
  File "/home/yang/dmcontrol-generalization-benchmark/src/env/dmc2gym/dmc2gym/__init__.py", line 36, in make
    if not env_id in gym.envs.registry.env_specs:
AttributeError: 'dict' object has no attribute 'env_specs'

**Comment by arjunmajum** [comment]
Here's a quick fix to line 36 in `dmc2gym/__init__.py`:

```diff
-    if not env_id in gym.envs.registry.env_specs:
+    if not env_id in gym.envs.registry:
```

**Comment by arjunmajum** [comment]
A temporary solution is reverting to an older version of gym:

```
pip install gym==0.25.2
```

**Comment by MyIDis12138** [comment]
> A temporary solution is reverting to an older version of gym:
> 
> ```
> pip install gym==0.25.2
> ```

downgrade gym solved my problems. Thanks
