### ISSUE TITLE
time_limit = None RunTime error

### ISSUE THREAD

**Issue by episodeyang** [denisyarats/dmc2gym#5]
When running the example, we got the following bug:

```python
import dmc2gym

env = dmc2gym.make(domain_name='point_mass', task_name='easy', seed=1)

done = False
obs = env.reset()
while not done:
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
```

## Error

```bash
/Users/ge/opt/anaconda3/envs/plan2vec/bin/python /Users/ge/fair/dm_control_suite_playground/dm_control_suite_playground/__init__.py
Traceback (most recent call last):
  File "/Users/ge/fair/dm_control_suite_playground/dm_control_suite_playground/__init__.py", line 3, in <module>
    env = dmc2gym.make(domain_name='point_mass', task_name='easy', seed=1)
  File "/Users/ge/fair/dmc2gym/dmc2gym/__init__.py", line 48, in make
    return gym.make(env_id)
  File "/Users/ge/opt/anaconda3/envs/plan2vec/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/Users/ge/opt/anaconda3/envs/plan2vec/lib/python3.6/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/Users/ge/opt/anaconda3/envs/plan2vec/lib/python3.6/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/Users/ge/fair/dmc2gym/dmc2gym/wrappers.py", line 64, in __init__
    environment_kwargs=environment_kwargs
  File "/Users/ge/opt/anaconda3/envs/plan2vec/lib/python3.6/site-packages/dm_control/suite/__init__.py", line 114, in load
    environment_kwargs, visualize_reward)
  File "/Users/ge/opt/anaconda3/envs/plan2vec/lib/python3.6/site-packages/dm_control/suite/__init__.py", line 148, in build_environment
    env = domain.SUITE[task_name](**task_kwargs)
  File "/Users/ge/opt/anaconda3/envs/plan2vec/lib/python3.6/site-packages/dm_control/suite/point_mass.py", line 49, in easy
    physics, task, time_limit=time_limit, **environment_kwargs)
  File "/Users/ge/opt/anaconda3/envs/plan2vec/lib/python3.6/site-packages/dm_control/rl/control.py", line 80, in __init__
    self._physics.timestep() * self._n_sub_steps)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

Process finished with exit code 1
```

**Comment by denisyarats** [comment]
I guess something has changed on the dm_control side, thanks for the PR.
